//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentScholarshipRegistration.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class scholarshipdetail
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please update the hilighted mandatory feilds")]
        public int student_Id { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please update the hilighted mandatory feilds")]
        public int Marks { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please update the hilighted mandatory feilds")]
        public string Grade { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please update the hilighted mandatory feilds")]
        public string DemoCourse { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please update the hilighted mandatory feilds")]
        public string College { get; set; }
    }
}
